# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2762258b6c1d3ecdcea543854fedd8903135075e07337c4c1b3147fc58ae4e044ad4bccbbe07382a71962f8f443095c40972c4fa48d305a060ce7aa52d6d57f5

test:
  secret_key_base: 95b8c12edb07306287f3799731e70c814a1bedc2f38db782825e1e087bee65e660b94ac1a6d8fa1fcd5bd74f9c34219fedd6daf6416aa1a82e4c7248fb96cb0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
